name: Remote Private Build

on:
  workflow_dispatch:
    inputs:
      job_type:
        description: "任务类型: build-only 或 ota"
        required: true
        default: "ota"
        type: choice
        options: [build-only, ota]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Workflow via API
        run: |
          REPO="${{ secrets.PRIVATE_REPO }}"          
          WORKFLOW="${{ secrets.PRIVATE_WORKFLOW }}" 
          
          # 开启 -sSf 模式，如果 Token 权限不够或名字写错，这里会直接飘红报错，方便排查
          curl -sSf -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW/dispatches \
            -d "{\"ref\":\"master\", \"inputs\": {\"job_type\": \"${{ github.event.inputs.job_type }}\"}}"
